/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HostsHostIdRouteImport } from './routes/hosts.$hostId'
import { Route as HostReportsRouteImport } from './routes/host.reports'
import { Route as HostRegisterRouteImport } from './routes/host.register'
import { Route as HostGalleryReviewRouteImport } from './routes/host.gallery-review'
import { Route as HostDashboardRouteImport } from './routes/host.dashboard'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as CheckInEventIdRouteImport } from './routes/check-in.$eventId'
import { Route as HostEventsNewRouteImport } from './routes/host.events.new'
import { Route as HostEventsEventIdEditRouteImport } from './routes/host.events.$eventId.edit'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsHostIdRoute = HostsHostIdRouteImport.update({
  id: '/hosts/$hostId',
  path: '/hosts/$hostId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostReportsRoute = HostReportsRouteImport.update({
  id: '/host/reports',
  path: '/host/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRegisterRoute = HostRegisterRouteImport.update({
  id: '/host/register',
  path: '/host/register',
  getParentRoute: () => rootRouteImport,
} as any)
const HostGalleryReviewRoute = HostGalleryReviewRouteImport.update({
  id: '/host/gallery-review',
  path: '/host/gallery-review',
  getParentRoute: () => rootRouteImport,
} as any)
const HostDashboardRoute = HostDashboardRouteImport.update({
  id: '/host/dashboard',
  path: '/host/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInEventIdRoute = CheckInEventIdRouteImport.update({
  id: '/check-in/$eventId',
  path: '/check-in/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostEventsNewRoute = HostEventsNewRouteImport.update({
  id: '/host/events/new',
  path: '/host/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HostEventsEventIdEditRoute = HostEventsEventIdEditRouteImport.update({
  id: '/host/events/$eventId/edit',
  path: '/host/events/$eventId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/tickets': typeof TicketsRoute
  '/check-in/$eventId': typeof CheckInEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/gallery-review': typeof HostGalleryReviewRoute
  '/host/register': typeof HostRegisterRoute
  '/host/reports': typeof HostReportsRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/events/new': typeof HostEventsNewRoute
  '/host/events/$eventId/edit': typeof HostEventsEventIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/tickets': typeof TicketsRoute
  '/check-in/$eventId': typeof CheckInEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/gallery-review': typeof HostGalleryReviewRoute
  '/host/register': typeof HostRegisterRoute
  '/host/reports': typeof HostReportsRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/events/new': typeof HostEventsNewRoute
  '/host/events/$eventId/edit': typeof HostEventsEventIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/tickets': typeof TicketsRoute
  '/check-in/$eventId': typeof CheckInEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/gallery-review': typeof HostGalleryReviewRoute
  '/host/register': typeof HostRegisterRoute
  '/host/reports': typeof HostReportsRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/events/new': typeof HostEventsNewRoute
  '/host/events/$eventId/edit': typeof HostEventsEventIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/my-events'
    | '/tickets'
    | '/check-in/$eventId'
    | '/events/$eventId'
    | '/host/dashboard'
    | '/host/gallery-review'
    | '/host/register'
    | '/host/reports'
    | '/hosts/$hostId'
    | '/invite/$token'
    | '/host/events/new'
    | '/host/events/$eventId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/my-events'
    | '/tickets'
    | '/check-in/$eventId'
    | '/events/$eventId'
    | '/host/dashboard'
    | '/host/gallery-review'
    | '/host/register'
    | '/host/reports'
    | '/hosts/$hostId'
    | '/invite/$token'
    | '/host/events/new'
    | '/host/events/$eventId/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/explore'
    | '/my-events'
    | '/tickets'
    | '/check-in/$eventId'
    | '/events/$eventId'
    | '/host/dashboard'
    | '/host/gallery-review'
    | '/host/register'
    | '/host/reports'
    | '/hosts/$hostId'
    | '/invite/$token'
    | '/host/events/new'
    | '/host/events/$eventId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  MyEventsRoute: typeof MyEventsRoute
  TicketsRoute: typeof TicketsRoute
  CheckInEventIdRoute: typeof CheckInEventIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  HostDashboardRoute: typeof HostDashboardRoute
  HostGalleryReviewRoute: typeof HostGalleryReviewRoute
  HostRegisterRoute: typeof HostRegisterRoute
  HostReportsRoute: typeof HostReportsRoute
  HostsHostIdRoute: typeof HostsHostIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  HostEventsNewRoute: typeof HostEventsNewRoute
  HostEventsEventIdEditRoute: typeof HostEventsEventIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId': {
      id: '/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof HostsHostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/reports': {
      id: '/host/reports'
      path: '/host/reports'
      fullPath: '/host/reports'
      preLoaderRoute: typeof HostReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/register': {
      id: '/host/register'
      path: '/host/register'
      fullPath: '/host/register'
      preLoaderRoute: typeof HostRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/gallery-review': {
      id: '/host/gallery-review'
      path: '/host/gallery-review'
      fullPath: '/host/gallery-review'
      preLoaderRoute: typeof HostGalleryReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/dashboard': {
      id: '/host/dashboard'
      path: '/host/dashboard'
      fullPath: '/host/dashboard'
      preLoaderRoute: typeof HostDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in/$eventId': {
      id: '/check-in/$eventId'
      path: '/check-in/$eventId'
      fullPath: '/check-in/$eventId'
      preLoaderRoute: typeof CheckInEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/events/new': {
      id: '/host/events/new'
      path: '/host/events/new'
      fullPath: '/host/events/new'
      preLoaderRoute: typeof HostEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/events/$eventId/edit': {
      id: '/host/events/$eventId/edit'
      path: '/host/events/$eventId/edit'
      fullPath: '/host/events/$eventId/edit'
      preLoaderRoute: typeof HostEventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  MyEventsRoute: MyEventsRoute,
  TicketsRoute: TicketsRoute,
  CheckInEventIdRoute: CheckInEventIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  HostDashboardRoute: HostDashboardRoute,
  HostGalleryReviewRoute: HostGalleryReviewRoute,
  HostRegisterRoute: HostRegisterRoute,
  HostReportsRoute: HostReportsRoute,
  HostsHostIdRoute: HostsHostIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  HostEventsNewRoute: HostEventsNewRoute,
  HostEventsEventIdEditRoute: HostEventsEventIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
